# Lab 2 - Classification tree and Kaggle competition

# **Name and Id:** Roy Paz 208421271

In this lab you will participate in a Kaggle competition:

https://www.kaggle.com/t/a85442f2e6f744f2b2cd06140001f127

In this competition you will train, test and submit the results to the competition. Use a decision tree while choosing how to preprocess the data and the model's parameters.

First, click the link and join the competition.

## set up:
Using 'kaggle.json' file from last lab, load the competition's data:

(remember to upload it to your environment)

You should have 3 files:

```
WineQT_train_set.csv
WineQT_test_set.csv
WineQT_sample_submission.csv - which is an example file to your submission

```

In [ ]:
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
!kaggle competitions download -c decision-trees-lab-2-wine-classification
! unzip /content/decision-trees-lab-2-wine-classification.zip

mkdir: cannot create directory ‘/root/.kaggle’: File exists
decision-trees-lab-2-wine-classification.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  /content/decision-trees-lab-2-wine-classification.zip
replace sample_submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: Y
  inflating: sample_submission.csv
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: Y
  inflating: test.csv
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: Y
  inflating: train.csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

train_set = pd.read_csv('/content/train.csv', index_col='Id')
train_set.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
Id,,,,,,,,,,,,
0,8.0,0.50,0.39,2.2,0.073,30.0,39.0,0.99572,3.33,0.77,12.1,6
1,9.3,0.30,0.73,2.3,0.092,30.0,67.0,0.99854,3.32,0.67,12.8,6
2,7.1,0.51,0.03,2.1,0.059,3.0,12.0,0.99660,3.52,0.73,11.3,7
3,8.1,0.87,0.22,2.6,0.084,11.0,65.0,0.99730,3.20,0.53,9.8,5
4,8.5,0.36,0.30,2.3,0.079,10.0,45.0,0.99444,3.20,1.36,9.5,6
5,9.9,0.51,0.44,2.2,0.111,30.0,134.0,0.99820,3.11,0.54,9.6,5
6,7.2,0.87,0.00,2.3,0.080,6.0,18.0,0.99552,3.34,0.60,11.3,6
7,7.5,0.43,0.32,1.8,0.066,18.0,40.0,0.99560,3.30,0.43,9.7,6
8,11.6,0.38,0.55,2.2,0.084,17.0,40.0,1.00080,3.17,0.73,9.8,6
9,7.8,0.78,0.09,2.2,0.049,13.0,29.0,0.99682,3.51,0.49,9.5,5

## Task 1:
Decide how to preprocess the data. Think about missing values, categorical values, normalization ect. I recommend analyzing missing values, distribution, mean values std values ect. to determine how to pre-process

(You can find information about the data and features on the competition page)

In [ ]:
train_set

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
Id,,,,,,,,,,,,
0,8.0,0.50,0.39,2.20,0.073,30.0,39.0,0.99572,3.33,0.77,12.1,6
1,9.3,0.30,0.73,2.30,0.092,30.0,67.0,0.99854,3.32,0.67,12.8,6
2,7.1,0.51,0.03,2.10,0.059,3.0,12.0,0.99660,3.52,0.73,11.3,7
3,8.1,0.87,0.22,2.60,0.084,11.0,65.0,0.99730,3.20,0.53,9.8,5
4,8.5,0.36,0.30,2.30,0.079,10.0,45.0,0.99444,3.20,1.36,9.5,6
...,...,...,...,...,...,...,...,...,...,...,...,...
2051,6.6,0.31,0.13,2.00,0.056,29.0,42.0,0.99388,3.52,0.87,12.0,7
2052,9.7,0.59,0.21,1.80,0.079,27.0,65.0,0.99745,3.14,0.58,9.4,5
2053,7.7,0.43,0.42,1.70,0.071,19.0,37.0,0.99258,3.32,0.77,12.5,8
2054,9.1,0.50,0.00,1.75,0.058,5.0,13.0,0.99670,3.22,0.42,9.5,5
2055,6.2,0.31,0.18,2.30,0.059,12.0,28.0,0.99520,3.56,0.88,11.4,7

In [ ]:
# implement here
# train_set.info() # non nulls
train_set.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,2056.000000,2056.000000,2056.000000,2056.000000,2056.000000,2056.000000,2056.000000,2056.000000,2056.000000,2056.000000,2056.000000,2056.000000
mean,8.365175,0.527601,0.265058,2.398881,0.081856,16.955982,49.236868,0.996748,3.310569,0.641308,10.414972,5.720817
std,1.705390,0.173164,0.188267,0.858824,0.023729,10.009710,32.961141,0.001827,0.142321,0.137942,1.028825,0.853146
min,5.000000,0.180000,0.000000,1.200000,0.012000,1.000000,7.000000,0.990070,2.740000,0.390000,8.700000,3.000000
25%,7.200000,0.390000,0.090000,1.900000,0.071000,8.000000,22.000000,0.995600,3.200000,0.550000,9.500000,5.000000
50%,7.950000,0.520000,0.250000,2.200000,0.079000,16.000000,44.000000,0.996700,3.310000,0.610000,10.100000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,24.000000,65.000000,0.997800,3.390000,0.720000,11.000000,6.000000
max,15.900000,1.580000,0.760000,14.000000,0.414000,68.000000,289.000000,1.003690,3.780000,1.950000,14.000000,8.000000

In [ ]:
train_set["quality"].value_counts() # non nulls

5    839
6    778
7    333
4     55
8     39
3     12
Name: quality, dtype: int64

In [ ]:
X = train_set.drop(['quality'], axis=1)
y = train_set['quality']

## Task 2:
Create a decision tree model - select it's parameters as you see fit.

Here you can use any tools and libraries you know to find and select the best model.

In [ ]:
# implemet here
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, balanced_accuracy_score

parameters = {"criterion": ['gini'],
              "max_depth": [2,3,4,6,8,10], "min_samples_split": [2,5,10,20,50,80,100,120],
              "max_features": [2,3,4,8,10,11,12], "min_samples_leaf": [100,120,140,160,180]}

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=32423423, test_size=0.2)
algorithm = DecisionTreeClassifier(random_state=342343)
clf = GridSearchCV(algorithm, parameters, cv= 10, n_jobs=-1)
clf.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(random_state=342343),
             n_jobs=-1,
             param_grid={'criterion': ['gini'],
                         'max_depth': [2, 3, 4, 6, 8, 10],
                         'max_features': [2, 3, 4, 8, 10, 11, 12],
                         'min_samples_leaf': [100, 120, 140, 160, 180],
                         'min_samples_split': [2, 5, 10, 20, 50, 80, 100, 120]})

In [ ]:
clf.best_params_

{'criterion': 'gini',
 'max_depth': 3,
 'max_features': 11,
 'min_samples_leaf': 100,
 'min_samples_split': 2}

In [ ]:
pred = clf.predict(X_test)
pred

array([6, 6, 7, 6, 5, 5, 5, 7, 7, 7, 5, 6, 5, 5, 5, 5, 5, 5, 5, 7, 5, 6,
       5, 6, 6, 5, 6, 5, 5, 5, 5, 5, 5, 5, 7, 6, 7, 7, 6, 5, 6, 7, 6, 5,
       6, 6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 6, 6, 6, 6, 7, 5, 5, 6, 5, 5,
       5, 5, 5, 5, 6, 5, 7, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 5, 6,
       5, 6, 6, 6, 6, 5, 6, 5, 6, 7, 7, 6, 5, 6, 6, 6, 6, 6, 6, 5, 7, 5,
       5, 7, 5, 7, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 5, 7, 5, 6, 5, 6, 5,
       6, 6, 6, 6, 7, 7, 5, 6, 5, 5, 6, 7, 7, 7, 5, 6, 5, 6, 5, 7, 5, 5,
       5, 7, 5, 5, 7, 5, 6, 6, 5, 5, 6, 6, 5, 5, 5, 6, 5, 5, 7, 5, 7, 7,
       6, 6, 6, 6, 5, 5, 5, 7, 5, 7, 6, 6, 5, 6, 5, 6, 6, 5, 5, 7, 6, 6,
       6, 5, 6, 6, 6, 6, 5, 6, 5, 7, 5, 7, 5, 5, 7, 6, 6, 5, 6, 5, 5, 5,
       7, 6, 6, 6, 5, 7, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 7, 5, 6, 5,
       5, 7, 5, 6, 5, 7, 5, 5, 5, 5, 6, 5, 5, 6, 5, 6, 5, 5, 7, 6, 5, 5,
       6, 5, 5, 5, 6, 5, 7, 6, 5, 6, 6, 6, 5, 6, 5, 5, 7, 7, 5, 6, 7, 5,
       6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 7, 6, 5, 6, 6, 6, 7, 5, 7, 5, 7, 6,
       5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 6, 7, 6,
       6, 7, 7, 5, 7, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 7, 5, 6, 6, 5, 5, 5,
       5, 7, 5, 5, 7, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 6, 7, 5, 6, 5, 5, 6, 5,
       6, 5, 5, 7, 6, 5, 5, 5, 5, 5, 5, 6, 6, 5, 5, 5])

In [ ]:
best_grid = clf.best_estimator_

In [ ]:
accuracy_score(list(y_test),list(pred))

0.5849514563106796

In [ ]:
balanced_accuracy_score(list(y_test),list(pred))

0.28983194489523606

## Task 3:
Create a predictions file. Use your trained model to make predictions on the test set and save the output to csv file named 'sample_submission.csv'.

Make sure to keep the ids of the test set (column 'Id') in your submission file. You have an example of this file named 'WineQT_sample_submission.csv' in the competition page on Kaggle and among the files you loaded.

After you create and save your submission file, upload it to Kaggle competition by clicking on the submission button and choosing the file. You can submit your predictions up to **5 times a day.**

In [ ]:
# implement here
test_set = pd.read_csv('/content/test.csv', index_col='Id')
test_set.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
Id,,,,,,,,,,,
2056,7.2,0.510,0.01,2.0,0.077,31.0,54.0,0.99748,3.39,0.59,9.8
2057,7.2,0.755,0.15,2.0,0.102,14.0,35.0,0.99586,3.33,0.68,10.0
2058,8.4,0.460,0.40,2.0,0.065,21.0,50.0,0.99774,3.08,0.65,9.5
2059,8.0,0.470,0.40,1.8,0.056,14.0,25.0,0.99480,3.30,0.65,11.7
2060,6.5,0.340,0.32,2.1,0.044,8.0,94.0,0.99356,3.23,0.48,12.8
2061,6.1,0.320,0.25,2.3,0.073,11.0,86.0,0.99464,3.16,0.70,11.2
2062,6.7,0.640,0.05,1.8,0.054,6.0,14.0,0.99456,3.35,0.58,10.9
2063,12.5,0.370,0.59,1.8,0.079,3.0,16.0,0.99940,3.16,0.68,10.5
2064,6.3,0.470,0.32,1.9,0.069,18.0,85.0,0.99580,3.39,0.55,14.0
2065,7.9,0.180,0.40,1.7,0.066,23.0,99.0,0.99914,3.31,0.62,10.0

In [ ]:
test_pred = clf.predict(test_set)
test_set["quality"] = test_pred

In [ ]:
from google.colab import files
test_set["quality"].to_csv('sample_submission.csv')
files.download("sample_submission.csv")

## Task 4:
Convert the notebook into html:


1.   Download the notebook by clicking the File tab
2.   In the directory of the file open cmd
3.   Run the command:
```
 jupyter nbconvert --to html notebook.ipynb
```

Or direcrtly from Colab:
```
 !jupyter nbconvert --to html notebook.ipynb
```

In [ ]:
!jupyter nbconvert --to html /content/Lab2.ipynb

[NbConvertApp] Converting notebook /content/Lab2.ipynb to html
[NbConvertApp] Writing 640095 bytes to /content/Lab2.html